services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.8-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${APP_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${APP_MONGO_PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 3080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${APP_MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${APP_MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
