services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.8-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo-admin
      - MONGO_INITDB_ROOT_PASSWORD=todoadmin1234!

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 3080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=todo-admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=todoadmin1234!
      - ME_CONFIG_MONGODB_SERVER=mongodb
